onecgiar-pr-client/src/app/custom-fields/sync-button/sync-button.component.html
onecgiar-pr-client/src/app/pages/results/pages/result-detail/components/share-request-modal/model/shareRequestBody.model.ts
onecgiar-pr-client/src/app/pages/results/pages/result-detail/components/share-request-modal/share-request-modal.component.html
onecgiar-pr-client/src/app/pages/results/pages/result-detail/components/share-request-modal/share-request-modal.component.ts
onecgiar-pr-client/src/app/pages/results/pages/result-detail/pages/rd-general-information/rd-general-information.component.html
onecgiar-pr-client/src/app/pages/results/pages/result-detail/pages/rd-general-information/rd-general-information.component.ts
onecgiar-pr-client/src/app/pages/results/pages/result-detail/pages/rd-geographic-location/rd-geographic-location.component.html
onecgiar-pr-client/src/app/pages/results/pages/result-detail/pages/rd-geographic-location/rd-geographic-location.component.ts
onecgiar-pr-client/src/app/pages/results/pages/result-detail/pages/rd-partners/rd-partners.component.ts
onecgiar-pr-client/src/app/pages/results/pages/result-detail/pages/rd-result-types-pages/knowledge-product-info/knowledge-product-info.component.html
onecgiar-pr-client/src/app/pages/results/pages/result-detail/pages/rd-result-types-pages/knowledge-product-info/knowledge-product-info.component.ts
onecgiar-pr-client/src/app/pages/results/pages/result-detail/pages/rd-result-types-pages/knowledge-product-info/model/knowledge-product-save.dto.ts
onecgiar-pr-client/src/app/pages/results/pages/result-detail/pages/rd-result-types-pages/knowledge-product-info/model/knowledgeProductBody.ts
onecgiar-pr-client/src/app/pages/results/pages/results-outlet/pages/results-list/results-list.component.ts
onecgiar-pr-client/src/app/pages/results/pages/results-outlet/pages/results-notifications/components/notification-item/notification-item.component.ts
onecgiar-pr-client/src/app/pages/results/pages/results-outlet/pages/results-notifications/results-notifications.component.html
onecgiar-pr-client/src/app/pages/results/pages/results-outlet/pages/results-notifications/results-notifications.module.ts
onecgiar-pr-client/src/app/pages/results/pages/results-outlet/results-outlet.component.html
onecgiar-pr-client/src/app/shared/services/api/results-api.service.ts
onecgiar-pr-server/src/api/results/result.repository.ts
onecgiar-pr-server/src/api/results/results-knowledge-products/dto/results-knowledge-product-save.dto.ts
onecgiar-pr-server/src/api/results/results-knowledge-products/entities/results-knowledge-product.entity.ts
onecgiar-pr-server/src/api/results/results-knowledge-products/results-knowledge-products.controller.ts
onecgiar-pr-server/src/api/results/results-knowledge-products/results-knowledge-products.mapper.ts
onecgiar-pr-server/src/api/results/results-knowledge-products/results-knowledge-products.service.ts
onecgiar-pr-server/src/api/results/results.service.ts
onecgiar-pr-server/src/clarisa/clarisa-initiatives/ClarisaInitiatives.repository.ts
onecgiar-pr-server/src/clarisa/clarisa-melia-study-type/clarisa-melia-study-type.controller.ts
onecgiar-pr-server/src/clarisa/clarisa-melia-study-type/clarisa-melia-study-type.module.ts
onecgiar-pr-server/src/clarisa/clarisa-melia-study-type/clarisa-melia-study-type.service.ts

:sparkles: feat(retrieve): add service to retrieve legacy results
:recycle: refactor(Validations): improved
:recycle: refactor(Sync button): added in section 1 3 4 7

fix(toc_id): toc_id correction is sent

---

onecgiar-pr-client/src/app/pages/results/pages/result-creator/result-creator.component.ts
onecgiar-pr-client/src/app/pages/results/pages/result-detail/pages/rd-general-information/models/generalInfoBody.ts
onecgiar-pr-client/src/app/pages/results/pages/result-detail/pages/rd-general-information/rd-general-information.component.html
onecgiar-pr-client/src/app/pages/results/pages/result-detail/pages/rd-general-information/rd-general-information.component.ts
onecgiar-pr-client/src/app/pages/results/pages/result-detail/pages/rd-result-types-pages/innovation-dev-info/innovation-dev-info.component.html
onecgiar-pr-client/src/app/pages/results/pages/result-detail/pages/rd-result-types-pages/innovation-dev-info/innovation-dev-info.component.ts
onecgiar-pr-client/src/app/pages/results/pages/result-detail/pages/rd-result-types-pages/innovation-dev-info/model/innovationDevInfoBody.ts
onecgiar-pr-client/src/app/pages/results/pages/results-outlet/pages/results-list/pipes/results-list-filter.pipe.ts
onecgiar-pr-client/src/app/pages/results/pages/results-outlet/pages/results-list/services/results-list-filter.service.ts
onecgiar-pr-client/src/app/shared/services/api/results-api.service.ts
onecgiar-pr-server/src/api/results/dto/create-general-information-result.dto.ts
onecgiar-pr-server/src/api/results/entities/result.entity.ts
onecgiar-pr-server/src/migrations/1669857400796-refactorresult.ts

:recycle: refactor(General information): hide url
:recycle: refactor(General information): hide url
:recycle: refactor(general information): lead_contact_person field added

fix{result}:fix type result

---

onecgiar-pr-client/src/app/custom-fields/custom-fields.module.ts
onecgiar-pr-client/src/app/custom-fields/custom-fields.scss
onecgiar-pr-client/src/app/custom-fields/pipes/yes-or-not-by-boolean.pipe.spec.ts
onecgiar-pr-client/src/app/custom-fields/pipes/yes-or-not-by-boolean.pipe.ts
onecgiar-pr-client/src/app/custom-fields/pr-button/pr-button.component.ts
onecgiar-pr-client/src/app/custom-fields/pr-input/pr-input.component.html
onecgiar-pr-client/src/app/custom-fields/pr-select/pr-select.component.html
onecgiar-pr-client/src/app/custom-fields/pr-select/pr-select.component.ts
onecgiar-pr-client/src/app/pages/results/pages/result-detail/pages/rd-general-information/rd-general-information.component.html
onecgiar-pr-client/src/app/pages/results/pages/result-detail/pages/rd-general-information/rd-general-information.component.ts
onecgiar-pr-client/src/app/pages/results/pages/result-detail/pages/rd-result-types-pages/innovation-dev-info/innovation-dev-info.component.html
onecgiar-pr-client/src/app/pages/results/pages/result-detail/pages/rd-result-types-pages/knowledge-product-info/knowledge-product-info.component.html
onecgiar-pr-client/src/app/pages/results/pages/result-detail/pages/rd-result-types-pages/policy-change-info/policy-change-info.component.html
onecgiar-pr-client/src/app/pages/results/pages/result-detail/pages/rd-result-types-pages/policy-change-info/policy-change-info.component.ts
onecgiar-pr-client/src/app/pages/results/pages/results-outlet/pages/results-list/results-list.component.ts
onecgiar-pr-client/src/app/pages/results/pages/results-outlet/pages/results-notifications/components/notification-item/notification-item.component.html
onecgiar-pr-client/src/app/pages/results/pages/results-outlet/pages/results-notifications/components/notification-item/notification-item.component.ts
onecgiar-pr-client/src/app/shared/services/api/api.service.ts
onecgiar-pr-client/src/app/shared/services/api/results-api.service.ts
onecgiar-pr-client/src/app/shared/services/global/innovation-control-list.service.ts

:sparkles: feat(notification-item): add spinner in notifications

:recycle: refactor(YesOrNotByBooleanPipe): created to boolean inputs

---

onecgiar-pr-client/src/app/pages/results/pages/result-detail/pages/rd-result-types-pages/knowledge-product-info/knowledge-product-info.component.html
onecgiar-pr-client/src/app/pages/results/pages/result-detail/pages/rd-result-types-pages/knowledge-product-info/knowledge-product-info.component.ts
onecgiar-pr-client/src/app/pages/results/pages/result-detail/pages/rd-result-types-pages/knowledge-product-info/model/knowledgeProductBody.ts
onecgiar-pr-client/src/app/shared/services/api/results-api.service.ts
onecgiar-pr-server/src/api/results/ost-melia-studies/dto/create-ost-melia-study.dto.ts
onecgiar-pr-server/src/api/results/ost-melia-studies/dto/melia-study.dto.ts
onecgiar-pr-server/src/api/results/ost-melia-studies/dto/update-ost-melia-study.dto.ts
onecgiar-pr-server/src/api/results/ost-melia-studies/ost-melia-studies.controller.spec.ts
onecgiar-pr-server/src/api/results/ost-melia-studies/ost-melia-studies.controller.ts
onecgiar-pr-server/src/api/results/ost-melia-studies/ost-melia-studies.module.ts
onecgiar-pr-server/src/api/results/ost-melia-studies/ost-melia-studies.repository.ts
onecgiar-pr-server/src/api/results/ost-melia-studies/ost-melia-studies.service.spec.ts
onecgiar-pr-server/src/api/results/ost-melia-studies/ost-melia-studies.service.ts
onecgiar-pr-server/src/api/results/results-knowledge-products/dto/results-knowledge-product.dto.ts
onecgiar-pr-server/src/api/results/results-knowledge-products/entities/results-knowledge-product.entity.ts
onecgiar-pr-server/src/api/results/results-knowledge-products/results-knowledge-products.mapper.ts
onecgiar-pr-server/src/api/results/results-knowledge-products/results-knowledge-products.service.ts
onecgiar-pr-server/src/api/results/results-toc-results/results-toc-results.repository.ts
onecgiar-pr-server/src/api/results/results.module.ts
onecgiar-pr-server/src/api/results/results.routes.ts
onecgiar-pr-server/src/api/results/share-result-request/share-result-request.service.ts
onecgiar-pr-server/src/migrations/1670012343284-addOSTMeliaStudyKP.ts

✨ feat(KP): Saving MELIA study
:bug: fix(share): failed to update

♻️ refactor(knowledge-product): loading/saving MELIA Study

---

onecgiar-pr-client/src/app/pages/results/pages/result-detail/components/partners-request/partners-request.component.html
onecgiar-pr-client/src/app/pages/results/pages/result-detail/components/partners-request/partners-request.component.scss
onecgiar-pr-client/src/app/pages/results/pages/result-detail/components/partners-request/partners-request.component.ts
onecgiar-pr-client/src/app/pages/results/pages/result-detail/pages/rd-general-information/rd-general-information.component.html
onecgiar-pr-client/src/app/pages/results/pages/result-detail/pages/rd-general-information/rd-general-information.component.ts
onecgiar-pr-client/src/app/pages/results/pages/result-detail/pages/rd-partners/components/knowledge-product-selector/knowledge-product-selector.component.html
onecgiar-pr-client/src/app/pages/results/pages/result-detail/pages/rd-partners/components/normal-selector/normal-selector.component.html
onecgiar-pr-client/src/app/pages/results/pages/result-detail/pages/rd-result-types-pages/cap-dev-info/cap-dev-info.component.html
onecgiar-pr-client/src/app/pages/results/pages/result-detail/pages/rd-result-types-pages/policy-change-info/policy-change-info.component.html
onecgiar-pr-client/src/app/pages/results/pages/result-detail/pages/rd-theory-of-change/rd-theory-of-change.component.html
onecgiar-pr-client/src/styles/containers.scss
onecgiar-pr-server/src/api/results/results-validation-module/results-validation-module.repository.ts

:bug: fix(cron): error when executing cron
:recycle: refactor(General information): and guides and add container
:recycle: refactor(General information): Lead contact person editable in KP

:recycle: refactor(General information): Fixed capitalization in the score

---

onecgiar-pr-client/src/app/custom-fields/pipes/yes-or-not-by-boolean.pipe.ts
onecgiar-pr-client/src/app/pages/results/pages/result-detail/components/retrieve-modal/retrieve-modal.service.ts
onecgiar-pr-client/src/app/pages/results/pages/result-detail/components/share-request-modal/share-request-modal.component.html
onecgiar-pr-client/src/app/pages/results/pages/result-detail/pages/rd-theory-of-change/components/shared/toc-initiative-out/toc-initiative-out.component.html
onecgiar-pr-client/src/app/pages/results/pages/result-detail/pages/rd-theory-of-change/components/toc-initiative-output-section/toc-initiative-output-section.component.html
onecgiar-pr-client/src/app/pages/results/pages/result-detail/pages/rd-theory-of-change/rd-theory-of-change.component.html
onecgiar-pr-client/src/app/pages/results/pages/result-detail/pages/rd-theory-of-change/rd-theory-of-change.component.ts
onecgiar-pr-client/src/app/pages/results/pages/result-detail/panel-menu/pipes/panel-menu.pipe.ts
onecgiar-pr-client/src/app/pages/results/pages/result-detail/result-detail.component.ts
onecgiar-pr-client/src/app/pages/results/pages/results-outlet/pages/results-notifications/components/notification-item/notification-item.component.ts
onecgiar-pr-client/src/app/shared/services/api/toc-api.service.ts
onecgiar-pr-client/src/app/shared/services/global/green-checks.service.ts
onecgiar-pr-server/src/api/results/share-result-request/share-result-request.service.ts

:bug: fix(share): the toc is not mapped when responding to a outcome reques…
:recycle: refactor(TOC): validations improved

:bug: fix(Request): Fix title and requester in request modal

---

onecgiar-pr-client/src/app/app.component.html
onecgiar-pr-client/src/app/custom-fields/pr-field-header/pr-field-header.component.html
onecgiar-pr-client/src/app/custom-fields/pr-field-header/pr-field-header.component.scss
onecgiar-pr-client/src/app/custom-fields/pr-field-header/pr-field-header.component.ts
onecgiar-pr-client/src/app/custom-fields/pr-input/pr-input.component.html
onecgiar-pr-client/src/app/pages/results/pages/result-detail/components/retrieve-modal/retrieve-modal.service.ts
onecgiar-pr-client/src/app/pages/results/pages/result-detail/components/share-request-modal/share-request-modal.component.html
onecgiar-pr-client/src/app/pages/results/pages/result-detail/pages/rd-geographic-location/rd-geographic-location.component.html
onecgiar-pr-client/src/app/pages/results/pages/result-detail/pages/rd-geographic-location/rd-geographic-location.component.scss
onecgiar-pr-client/src/app/pages/results/pages/result-detail/pages/rd-geographic-location/rd-geographic-location.component.ts
onecgiar-pr-client/src/app/pages/results/pages/result-detail/pages/rd-links-to-results/rd-links-to-results.component.html
onecgiar-pr-client/src/app/pages/results/pages/result-detail/pages/rd-links-to-results/rd-links-to-results.component.ts
onecgiar-pr-client/src/app/pages/results/pages/result-detail/pages/rd-result-types-pages/cap-dev-info/cap-dev-info.component.html
onecgiar-pr-client/src/app/pages/results/pages/result-detail/pages/rd-result-types-pages/cap-dev-info/cap-dev-info.component.ts
onecgiar-pr-client/src/app/pages/results/pages/result-detail/pages/rd-result-types-pages/innovation-dev-info/innovation-dev-info.component.html
onecgiar-pr-client/src/app/pages/results/pages/result-detail/pages/rd-result-types-pages/innovation-dev-info/innovation-dev-info.component.ts
onecgiar-pr-client/src/app/pages/results/pages/result-detail/pages/rd-result-types-pages/policy-change-info/policy-change-info.component.html
onecgiar-pr-client/src/app/pages/results/pages/result-detail/pages/rd-theory-of-change/components/shared/toc-initiative-out/toc-initiative-out.component.html
onecgiar-pr-client/src/app/pages/results/pages/result-detail/pages/rd-theory-of-change/components/toc-action-area-outcome-section/toc-action-area-outcome-section.component.html
onecgiar-pr-client/src/app/pages/results/pages/result-detail/result-detail.component.scss
onecgiar-pr-client/src/app/pages/results/pages/results-outlet/pages/results-notifications/components/notification-item/notification-item.component.ts
onecgiar-pr-client/src/app/shared/services/api/results-api.service.ts
onecgiar-pr-client/src/styles/fonts.scss

:recycle: refactor(policy-change-info): Select stages, name format improved
:recycle: refactor(rd-links-to-results): result list counter fixed
:recycle: refactor(readiness_of_this_innovation_description): added
:recycle: refactor(Results_portfolio_description): added

Add guidance

---

onecgiar-pr-client/src/app/custom-fields/pr-input/pr-input.component.html
onecgiar-pr-client/src/app/custom-fields/pr-multi-select/pr-multi-select.component.html
onecgiar-pr-client/src/app/custom-fields/pr-radio-button/pr-radio-button.component.html
onecgiar-pr-client/src/app/custom-fields/pr-select/pr-select.component.html
onecgiar-pr-client/src/app/custom-fields/pr-textarea/pr-textarea.component.html
onecgiar-pr-client/src/app/custom-fields/pr-yes-or-not/pr-yes-or-not.component.html
onecgiar-pr-client/src/app/pages/results/pages/result-detail/pages/rd-partners/components/normal-selector/normal-selector.component.html
onecgiar-pr-client/src/app/pages/results/pages/results-outlet/pages/results-notifications/components/notification-item/notification-item.component.html
onecgiar-pr-client/src/app/shared/routing/routing-data.ts
onecgiar-pr-server/src/api/results/share-result-request/share-result-request.repository.ts

:recycle: refactor(share result): add usernames
:bug: fix(Custom fields): this.dataControlSE?.currentResult?.status convert
:recycle: refactor(Routing): Quality Assurance underConstruction removed

:recycle: refactor(Notification): approved named added, and arrow removed to pe

---

onecgiar-pr-client/src/app/pages/results/pages/result-detail/pages/rd-result-types-pages/knowledge-product-info/knowledge-product-info.component.html
onecgiar-pr-client/src/app/pages/results/pages/result-detail/panel-menu/panel-menu.component.html
onecgiar-pr-client/src/app/pages/results/pages/result-detail/panel-menu/panel-menu.component.ts
onecgiar-pr-client/src/app/pages/results/pages/result-detail/result-detail.component.ts
onecgiar-pr-client/src/app/shared/services/current-result.service.ts
onecgiar-pr-server/src/toc/toc-results/toc-results.repository.ts

:recycle: refactor(Knowledge product): texts improved
:recycle: refactor(Submit button): Validation to hide, improved (Member)

:bug: fix(toc result): fixed work package name combinatorics error

---

onecgiar-pr-client/src/app/pages/admin-section/admin-section.component.ts
onecgiar-pr-client/src/app/pages/admin-section/pages/completeness-status/completeness-status.component.html
onecgiar-pr-client/src/app/pages/admin-section/pages/completeness-status/completeness-status.component.ts
onecgiar-pr-client/src/app/pages/admin-section/pages/completeness-status/components/result-history-of-changes-modal/result-history-of-changes-modal.component.html
onecgiar-pr-client/src/app/pages/admin-section/pages/user-report/user-report.component.html
onecgiar-pr-client/src/app/pages/results/pages/result-detail/pages/rd-links-to-results/rd-links-to-results.component.ts
onecgiar-pr-client/src/app/shared/routing/routing-data.ts
onecgiar-pr-server/src/api/results/linked-results/linked-results.repository.ts
onecgiar-pr-server/src/api/results/linked-results/linked-results.service.ts

[41719, 42106] Section 5 - Links to previous portfolio results are not being saved.

Fix - Links to previous portfolio results are not being saved and improve Admin Module

---

onecgiar-pr-client/src/app/pages/ipsr/pages/innovation-package-detail/innovation-package-detail.component.html

…dation added to show submit button

* Fixed Innovation-package-detail: validation was added for admin to show submit button

---

onecgiar-pr-server/src/api/ipsr/innovation-pathway/repository/result-ip-action-area-outcome.repository.ts

*Fixed (AA-O) Added version id according to old structure

---

onecgiar-pr-client/src/app/pages/results/pages/results-outlet/pages/results-list/components/results-to-update-modal/results-to-update-modal.component.html
onecgiar-pr-client/src/app/shared/components/change-phase-modal/change-phase-modal.component.html

…'Update Result' button on capacity change results type for admins

* refactor: Removed validation to enable the 'Update Result' button on capacity change results type for admins.

---

onecgiar-pr-client/src/app/pages/init-admin-section/pages/init-general-results-report/init-general-results-report.component.html

BUG init-general-results-report

---

onecgiar-pr-client/src/app/pages/ipsr/pages/innovation-package-detail/pages/ipsr-innovation-use-pathway/pages/step-n1/step-n1.component.ts
onecgiar-pr-client/src/app/shared/components/geoscope-management/geoscope-management.component.html
onecgiar-pr-server/src/api/results/result-countries/result-countries.service.ts

* Refactor Results module: Optimize non-pooled project budget retrieval.
* Refactor IPSR module: Mandatory data for step 1 adjusted.

* Feat performance improvements and bug fixes

---

onecgiar-pr-server/src/result-dashboard-bi/bi-reports/bi-reports.controller.ts
onecgiar-pr-server/src/result-dashboard-bi/bi-reports/repository/bi-report.repository.ts

:recycle: refactor: Added try catch and fixed controller method

---

onecgiar-pr-client/src/app/pages/type-one-report/pages/tor-key-results/tor-key-results.component.ts

:recycle: refactor(T1R): updated keyResultsDesc text in tor-key-results

---

onecgiar-pr-client/src/app/pages/ipsr/pages/innovation-package-list-content/pages/innovation-package-list/components/innovation-package-custom-table/innovation-package-custom-table.component.html
onecgiar-pr-client/src/app/pages/pdf-reports/pdf-reports.component.ts
onecgiar-pr-client/src/app/pages/results/pages/result-detail/components/pdf-actions/pdf-actions.component.ts
onecgiar-pr-client/src/app/pages/results/pages/results-outlet/pages/results-list/results-list.component.html
onecgiar-pr-client/src/app/shared/routing/routing-data.ts

*Refactor. refactor PDF report URLs to use new routes

---

.github/workflows/jenkins-trigger.yml

:recycle: refactor(project): Add action to trigger pipeline on code changes

:recycle: refactor(project): Add action to trigger pipeline on code changes

---

.github/workflows/jenkins-trigger.yml

:sparkles: feat(project): Add action to trigger pipeline on code changes

:sparkles: feat(project): Add action to trigger pipeline on code changes

---

.github/workflows/jenkins-trigger.yml
onecgiar-pr-server/src/api/platform-report/platform-report.service.ts

This pull request includes changes to trigger a Jenkins job on any branch push and a small modification to the `PlatformReportService` class to use a cleaned result code input when generating filenames.
* [`.github/workflows/jenkins-trigger.yml`](diffhunk://#diff-ece632ebc3c8f5f8c8fff3f5547d814124811ea82711e33ee81616f8bcd784bfR1-R29): Added a new GitHub Actions workflow to trigger a Jenkins job on any branch push and allow manual triggering. The workflow includes steps to get the branch name, build the Jenkins URL, and execute a curl command to trigger the job.
* [`onecgiar-pr-server/src/api/platform-report/platform-report.service.ts`](diffhunk://#diff-081634437ce6d32bfe3d099d96dd5e27538e6524bb5699293b68ffd9a03a4be8L261-R261): Modified the `PlatformReportService` class to use …

* Feat Improved the handling of PDF generation.

---

onecgiar-pr-client/src/app/shared/routing/routing-data.ts

*Fix. update underConstruction status for outcome indicators module

---

onecgiar-pr-server/src/api/contribution-to-indicators/repositories/contribution-to-indicator-result.repository.ts
onecgiar-pr-server/src/api/contribution-to-indicators/repositories/contribution-to-indicators.repository.ts

This pull request includes changes to improve the readability and functionality of the `new-complementary-innovation.component.ts` file and to update the labels in the `rd-general-information.component.html` file.
* [`onecgiar-pr-client/src/app/pages/ipsr/pages/innovation-package-detail/pages/ipsr-innovation-use-pathway/pages/step-n2/pages/complementary-innovation/components/new-complementary-innovation/new-complementary-innovation.component.ts`](diffhunk://#diff-b1a797e63779c3de7831718d3ba4da1d44cb3457fed6b8c372ca17c5f32dafb7L36-R53): Modified the `disableSaveButton` method to include a check for `other_funcions` in addition to `selectedValues`.
* [`onecgiar-pr-client/src/app/pages/results/pages/result-detail/pages/rd-general-information/rd-general-information.component.html`](diffhunk:// …

♻️ refactor. improve the readability, functionality and bug fixes

---

onecgiar-pr-client/src/app/pages/outcome-indicator/pages/indicator-details/indicator-details.component.ts
onecgiar-pr-client/src/app/pages/results/pages/result-detail/pages/rd-evidences/evidence-item/evidence-item.component.ts
onecgiar-pr-client/src/app/shared/routing/routing-data.ts
onecgiar-pr-client/src/app/shared/services/variables/global-links.service.ts

This pull request includes several changes to improve functionality and enhance user experience across multiple components. The most important changes include updates to the `IndicatorDetailsComponent`, `EvidenceItemComponent`, routing configurations, and the `GlobalLinksService`.
* Modified the `handleSaveIndicatorData` method to accept a parameter `isFirstTime` and updated its invocations accordingly. This change ensures a success message is displayed only when the data is saved after the initial load. [[1]](diffhunk://#diff-a9386474ea8a7b32142c513ef300973a43679d2fcf25f144c48a1d01ba7dcea7L98-R98) [[2]](diffhunk://#diff-a9386474ea8a7b32142c513ef300973a43679d2fcf25f144c48a1d01ba7dcea7L131-R131) [[3]](diffhunk://#diff-a9386474ea8a7b32142c513ef300973a43679d2fcf25f144c48a1d01ba7dcea7R140-R143 …

♻️ Refactor: Bug fixes and performance improvements

---

onecgiar-pr-server/src/api/platform-report/platform-report.service.ts

This pull request includes updates to the `PlatformReportService` class in the `onecgiar-pr-server/src/api/platform-report/platform-report.service.ts` file. The changes focus on improving the PDF generation process and enhancing the logging and validation mechanisms.
Improvements to PDF generation and fetching:
* Added `credentials` to the `info` object to include authentication headers for better security.
* Modified the PDF generation method to emit an event and fetch the generated PDF URL instead of directly returning the PDF.
Enhancements to logging and validation:
* Updated the logging message to include the file name and bucket name for better traceability.
* Changed the URL for the file validation request to a more specific endpoint for improved clarity and accuracy.

* Feat Update PDF generation process and improve error handling

---

onecgiar-pr-server/src/api/results/results-knowledge-products/results-knowledge-products.service.ts

This pull request introduces several changes to the `ResultsKnowledgeProductsService` class in the `onecgiar-pr-server` project. The main focus of these changes is to refactor the code for validating the existence of knowledge products by handle and to improve code readability and maintainability.
Key changes include:
* Added a new method `validateKPExistanceByHandle` to handle the logic of checking if a knowledge product already exists and returning the appropriate response. This method centralizes the validation logic, making the code more modular and easier to maintain.
* Introduced a helper method `extractHandleIdentifier` to extract the handle identifier from a raw URL. This method simplifies the code by removing duplicate logic for extracting the handle identifier.
* Refactored the …

♻️refactor(KP): leaving handle validation to M-QAP on first instance

---

onecgiar-pr-client/src/app/pages/outcome-indicator/outcome-indicator.component.ts
onecgiar-pr-client/src/app/pages/outcome-indicator/pages/eioi-home/eoio-home.component.html
onecgiar-pr-client/src/app/pages/outcome-indicator/pages/eioi-home/eoio-home.component.scss
onecgiar-pr-client/src/app/pages/outcome-indicator/pages/eioi-home/eoio-home.component.spec.ts
onecgiar-pr-client/src/app/pages/outcome-indicator/pages/eioi-home/eoio-home.component.ts
onecgiar-pr-client/src/app/pages/outcome-indicator/pages/indicator-details/components/details-table/details-table.component.html
onecgiar-pr-client/src/app/pages/outcome-indicator/pages/indicator-details/components/indicator-results-modal/column-filter/column-filter.component.html
onecgiar-pr-client/src/app/pages/outcome-indicator/pages/indicator-details/components/indicator-results-modal/column-filter/column-filter.component.scss
onecgiar-pr-client/src/app/pages/outcome-indicator/pages/indicator-details/components/indicator-results-modal/column-filter/column-filter.component.spec.ts
onecgiar-pr-client/src/app/pages/outcome-indicator/pages/indicator-details/components/indicator-results-modal/column-filter/column-filter.component.ts
onecgiar-pr-client/src/app/pages/outcome-indicator/pages/indicator-details/components/indicator-results-modal/indicator-results-modal.component.html
onecgiar-pr-client/src/app/pages/outcome-indicator/pages/indicator-details/components/indicator-results-modal/indicator-results-modal.component.scss
onecgiar-pr-client/src/app/pages/outcome-indicator/pages/indicator-details/components/indicator-results-modal/indicator-results-modal.component.ts
onecgiar-pr-client/src/app/pages/outcome-indicator/pages/outcome-indicator-home/outcome-indicator-home.component.spec.ts
onecgiar-pr-client/src/app/pages/outcome-indicator/pages/outcome-indicator-home/outcome-indicator-home.component.ts
onecgiar-pr-client/src/app/pages/outcome-indicator/pages/wp-home/wp-home.component.html
onecgiar-pr-client/src/app/pages/outcome-indicator/pages/wp-home/wp-home.component.scss
onecgiar-pr-client/src/app/pages/outcome-indicator/pages/wp-home/wp-home.component.spec.ts
onecgiar-pr-client/src/app/pages/outcome-indicator/pages/wp-home/wp-home.component.ts
onecgiar-pr-client/src/app/pages/outcome-indicator/services/outcome-indicator.service.test.ts
onecgiar-pr-client/src/app/pages/outcome-indicator/services/outcome-indicator.service.ts
onecgiar-pr-client/src/app/shared/services/export-tables.service.ts

This pull request introduces several updates to the outcome indicator components, focusing on functionality enhancements and UI improvements. The key changes include adding new services, updating the UI for better user experience, and enhancing the export functionality.
* Added `OutcomeIndicatorService` and `ExportTablesService` to handle data operations and exporting functionalities in `EoioHomeComponent`. [[1]](diffhunk://#diff-ca62a7796fdc5baaf136a5fe39c30f0b778426d4e08044d30b05d13b83d868d0R35-R37) [[2]](diffhunk://#diff-4264d535beae076ae78f4488d69eb86d0679c0057c629565b2412fee700e52a3R6-R27) [[3]](diffhunk://#diff-f583cfb098e016ce2d09b7c31bf9d6ad44c3e1511d2bfc133928d8d3ff864c48R12-R88)
* Implemented `exportProgressEoioExcel` method to enable downloading of outcome indicators as an …

*Feat. Added initiative, phase and category filtering and excel report functionality

---

onecgiar-pr-server/src/api/results/results-toc-results/results-toc-results.service.ts
onecgiar-pr-server/src/api/results/results-validation-module/results-validation-module.repository.ts
onecgiar-pr-server/src/api/results/results_by_inititiatives/resultByInitiatives.repository.ts
onecgiar-pr-server/src/api/results/share-result-request/share-result-request.service.ts

This pull request includes significant refactoring and improvements to the `ResultsTocResultsService` class and related repositories in the `onecgiar-pr-server` project. The changes focus on simplifying the code, improving error handling, and optimizing database operations.
Improvements to `ResultsTocResultsService`:
* Removed redundant `initiativeArrayRtr` variable and its associated logic for updating results by initiative.
* Simplified the logic for handling `createResultsTocResultDto` and mapped multiple work packages to initiatives using more efficient methods. [[1]](diffhunk://#diff-d37e49c54f4fdd2aa65662c27bdba2bf389aea837bf6a3a58e0aa42d983d89f1L720-R762) [[2]](diffhunk://#diff-d37e49c54f4fdd2aa65662c27bdba2bf389aea837bf6a3a58e0aa42d983d89f1L787-R787)
* Improved error handling by …

* Feat Improved Mapping from notification modulo and optimizing database operations

---

onecgiar-pr-client/src/app/pages/results/pages/result-detail/components/partners-request/models/partnersRequestBody.model.ts
onecgiar-pr-client/src/app/pages/results/pages/result-detail/components/partners-request/partners-request.component.ts
onecgiar-pr-client/src/app/shared/services/api/results-api.service.spec.ts
onecgiar-pr-server/src/clarisa/clarisa-connections/clarisa-connections.service.ts
onecgiar-pr-server/src/clarisa/clarisa-connections/dto/create-clarisa-connection.dto.ts

This pull request includes several changes to the `PartnersRequestComponent` and related files to enhance the partner request functionality by adding a new `platformUrl` field and improving error handling and code clarity.
Changes to `PartnersRequestComponent`:
* Added `platformUrl` field to `PartnersRequestBody` model (`partnersRequestBody.model.ts`).
* Imported `Router` and `environment` in `partners-request.component.ts` to construct the `platformUrl` dynamically.
* Modified the constructor of `PartnersRequestComponent` to include `Router` and refactored the `onRequestPartner` method to include `platformUrl` in the request body. [[1]](diffhunk://#diff-190a588540729f5350590ee06fb0c101196d44e93c7a09dedab2a1833b464a82L19-L26) [[2]](diffhunk://#diff-190a588540729f5350590ee06fb0c101196d44e93 …

* Feat Added new parameters for the composition of the Partner Request email.

---

onecgiar-pr-server/src/api/contribution-to-indicators/repositories/contribution-to-indicator-result.repository.ts

This pull request includes significant changes to the `getContributingResultsQuery` method in the `ContributionToIndicatorResultsRepository` class to improve readability and maintainability. The changes involve reformatting the SQL query and modifying the logic for checking active results and contributions.
* Reformatted the SQL query in the `getContributingResultsQuery` method to improve readability by breaking down the select statement into multiple lines.
* Replaced the subquery in the `where` clause with a `NOT EXISTS` clause to improve the logic for checking active results and contributions.

* Feat Added new validation for Outcome Indicators Module

---

onecgiar-pr-client/src/app/pages/admin-section/admin-section.component.ts
onecgiar-pr-client/src/app/pages/admin-section/pages/tickets-dashboard/tickets-dashboard.component.html
onecgiar-pr-client/src/app/pages/admin-section/pages/tickets-dashboard/tickets-dashboard.component.scss
onecgiar-pr-client/src/app/pages/admin-section/pages/tickets-dashboard/tickets-dashboard.component.spec.ts
onecgiar-pr-client/src/app/pages/admin-section/pages/tickets-dashboard/tickets-dashboard.component.ts
onecgiar-pr-client/src/app/shared/routing/routing-data.ts
onecgiar-pr-client/src/app/shared/services/variables/global-links.service.ts

This pull request introduces a new feature to the admin section of the application: a Tickets Dashboard. The changes involve adding new routes, components, and styles to support this feature. The most important changes include the addition of the Tickets Dashboard component, its associated HTML and SCSS files, and updates to the routing and service files.
* [`onecgiar-pr-client/src/app/pages/admin-section/admin-section.component.ts`](diffhunk://#diff-82ec3889775fb2af03ba6f138a5a0451e240647f337c0c6c6e5bbb66ae78aa91L14-R15): Added a new menu item for the Tickets Dashboard in the admin section.
* [`onecgiar-pr-client/src/app/pages/admin-section/pages/tickets-dashboard/tickets-dashboard.component.ts`](diffhunk://#diff-40dc2ba11e1f838c8dd5820b5fc4785767dd4a4eea824b63c02d92062f900bdcR1-R32): …

* Feat Implement Ticket Dashboard into Admin Module

---

onecgiar-pr-client/src/app/pages/admin-section/pages/tickets-dashboard/tickets-dashboard.component.html
onecgiar-pr-client/src/app/pages/admin-section/pages/tickets-dashboard/tickets-dashboard.component.scss
onecgiar-pr-client/src/app/pages/admin-section/pages/tickets-dashboard/tickets-dashboard.component.spec.ts
onecgiar-pr-client/src/app/pages/admin-section/pages/tickets-dashboard/tickets-dashboard.component.ts
onecgiar-pr-client/src/app/shared/services/logger.service.ts

This pull request includes significant updates to the `TicketsDashboardComponent` in the admin section of the application. The changes primarily focus on improving the iframe's adaptive height functionality, enhancing the component's lifecycle management, and updating related tests.
Improvements to iframe adaptive height:
* [`onecgiar-pr-client/src/app/pages/admin-section/pages/tickets-dashboard/tickets-dashboard.component.html`](diffhunk://#diff-738b0bc826222681a90b8582972fe73ae722d4fa9997c1f0b35727014076b577L14-R22): Added properties to the iframe element to support adaptive height, including `scrolling`, `frameborder`, and inline styles.
* [`onecgiar-pr-client/src/app/pages/admin-section/pages/tickets-dashboard/tickets-dashboard.component.scss`](diffhunk://#diff-24c3267e98bc55fcffcb0b05 …

* Feat Improved the dynamic handling of the iframe height for the Ticket embedding

---

onecgiar-pr-client/src/app/pages/ipsr/pages/innovation-package-detail/innovation-package-detail.component.html
onecgiar-pr-client/src/app/pages/ipsr/pages/innovation-package-detail/innovation-package-detail.component.ts
onecgiar-pr-client/src/app/pages/ipsr/services/ipsr-data-control.service.ts
onecgiar-pr-server/src/api/ipsr/innovation-pathway/innovation-pathway-step-four.service.spec.ts
onecgiar-pr-server/src/api/ipsr/innovation-pathway/innovation-pathway-step-four.service.ts
onecgiar-pr-server/src/api/ipsr/innovation-pathway/test/innovation-pathway-step-four.service.spec.ts
onecgiar-pr-server/src/api/ipsr/results-innovation-packages-validation-module/results-innovation-packages-validation-module.repository.ts
onecgiar-pr-server/src/api/ipsr/results-innovation-packages-validation-module/results-innovation-packages-validation-module.service.ts

This pull request introduces several changes to both the client and server codebases, focusing on improving code quality, adding new functionality, and refining error handling. Key updates include making variables `readonly`, adding a new property to the `DetailData` interface, and modifying SQL queries and error handling logic in the server-side service. Below is a categorized summary of the most important changes:
* **HTML Template Update**: Added a `keyup` event to the `<app-pr-button>` component to handle keyboard interactions for submission/unsubmission actions. (`innovation-package-detail.component.html`, [onecgiar-pr-client/src/app/pages/ipsr/pages/innovation-package-detail/innovation-package-detail.component.htmlL23-R24](diffhunk://#diff-6e4da999c91aea1296129c0e86ce6ef48dacaa2e8267 …

* Feat Adjust Fetch and Save from Step 4 of IPSR Module

---

onecgiar-pr-server/src/auth/modules/user/user.controller.ts
onecgiar-pr-server/src/auth/modules/user/user.service.ts

This pull request focuses on cleaning up logging statements and modifying user-related configurations in the `UserController` and `UserService` classes. The changes aim to streamline the codebase and improve error handling while adjusting some default user properties.
* [`onecgiar-pr-server/src/auth/modules/user/user.controller.ts`](diffhunk://#diff-e381d2f964afc6e62938f63d5127ba1a9948988d2f902f01a85d03e6477056b6L94-R94): Updated the default value of the `is_cgiar` property in the user object from `true` to `false`.
* [`onecgiar-pr-server/src/auth/modules/user/user.service.ts`](diffhunk://#diff-ad79eec486357e689e4ca1c484bec236c1da986810b82012d9908de5f2346e22L109-R112): Removed several `console.log` statements, including logs for the `cognitoPayload`, `currentUser`, and query results, to …

♻️Refactor: Update user creation logic to set is_cgiar to false and remove debug logs

---

onecgiar-pr-server/src/auth/modules/user/user.service.ts

This pull request includes minor updates to the `UserService` class in the `onecgiar-pr-server/src/auth/modules/user/user.service.ts` file. The changes primarily involve cleanup and additions to the template data.
Template data improvements:
* Added a new `logoUrl` field to the `templateData` object to support dynamic logo rendering in templates.
Code cleanup:
* Removed an unnecessary `console.log` statement for `createUserDto` to reduce clutter in the code.
* Removed an extraneous blank line before the `cognitoPayload` object definition for better code readability.

♻️ Refactor: Remove debug log from user creation and add logoUrl variable to template

---

onecgiar-pr-client/Dockerfile
onecgiar-pr-client/nginx.conf
onecgiar-pr-server/Dockerfile

This pull request introduces Docker support for both the client (`onecgiar-pr-client`) and server (`onecgiar-pr-server`) applications, along with a custom Nginx configuration for serving the client application. The changes include multi-stage Docker builds for optimized development, testing, and production environments, as well as a tailored Nginx setup for handling routing in a single-page application.
* **Multi-stage Dockerfile for Client**: Added a multi-stage Dockerfile to handle separate build, testing, and production stages. This includes using Node.js for building and testing, and Nginx for serving the production build.
* **Custom Nginx Configuration**: Added an `nginx.conf` file to configure Nginx for serving the Angular application, including SPA routing and a custom 404 error …

♻️ Refactor: Add Dockerfile and nginx configuration for client and server setup

---

.cursorrules
.github/workflows/cypress-cron.yml
.github/workflows/cypress.yml
onecgiar-pr-client/.github/workflows/cypress.yml
onecgiar-pr-client/.gitignore
onecgiar-pr-client/cypress.config.js
onecgiar-pr-client/cypress/README.md
onecgiar-pr-client/cypress/e2e/app.cy.ts
onecgiar-pr-client/cypress/e2e/login-simplified.cy.ts
onecgiar-pr-client/cypress/e2e/login.cy.ts
onecgiar-pr-client/cypress/e2e/results-list.cy.ts
onecgiar-pr-client/cypress/fixtures/example.json
onecgiar-pr-client/cypress/support/commands.ts
onecgiar-pr-client/cypress/support/e2e.ts
onecgiar-pr-client/cypress/tsconfig.json
onecgiar-pr-client/gemini.md
onecgiar-pr-client/package-lock.json
onecgiar-pr-client/package.json
onecgiar-pr-client/tsconfig.json

This pull request introduces significant updates to the Cypress E2E testing framework for the `onecgiar-pr-client` project, along with enhanced security practices and CI/CD workflow configurations. The changes include new test cases, configuration files, and workflows to improve automated testing and security compliance.
* [`.cursorrules`](diffhunk://#diff-315161dd3154081cb28d119355d3dd6de62ddc800ac1a12f8eb903e59047a018R1-R43): Added critical security rules to prevent exposure of sensitive information, including tokens and credentials, in logs, debugging outputs, and application code. Best practices and safe alternatives are documented.
* [`.github/workflows/cypress-cron.yml`](diffhunk://#diff-a9582fd73d0be1aabbf4d0d597a6fb3219432a7f2f23f7251aa6d7e999ef025aR1-R217): Created a new workflow …

:sparkles: feat: Cypress config - cron
