- onecgiar-pr-server/src/api/results/evidences/evidences.repository.ts
We’ve fixed a pesky bug where an empty evidence list would sneak in and break the SQL query. If the evidence list (`evidenceIdList`) was empty, it would generate an invalid SQL query like `id IN ()`, causing a syntax error. No more! We’ve plugged that hole.
Now, the activation query for evidences only runs if the list of evidence IDs actually contains something. If `evidenceIdList` is empty, we skip the activation query entirely and only deactivate the necessary evidences. It’s like making sure you don’t order pizza when you’re not even hungry!
By checking if the `evidenceIdListString` is empty before constructing the SQL query, we’ve ensured no invalid `IN ()` clauses can be executed. This small change means you’ll no longer see SQL errors like:
```
QueryFailedError: You have an error in …
```
> * Feat performance improvements and bug fixes

- onecgiar-pr-server/src/api/results/entities/result.entity.ts
- onecgiar-pr-server/src/api/user-notification-settings/user-notification-settings.service.spec.ts
- onecgiar-pr-server/src/auth/modules/user/entities/user.entity.ts
- onecgiar-pr-server/src/migrations/1729692807743-AddedQATrackingColumnsForResults.ts
This pull request introduces QA tracking fields to the `Result` entity, updates related entities, and includes a migration script to handle the new database schema changes.
* [`onecgiar-pr-server/src/api/results/entities/result.entity.ts`](diffhunk://#diff-8bb1e13a6a4d42010507c4756306dede49254ad3a6414fd123436546404e3d08R354-R381): Added new columns `qaed_date`, `qaed_comment`, and `qaed_user` to the `Result` entity. Also established a relationship with the `User` entity for the `qaed_user` field.
* [`onecgiar-pr-server/src/auth/modules/user/entities/user.entity.ts`](diffhunk://#diff-b247fcdbc6ae4ba1d7aceec868c0edb79cf030b0c43935a8c3df1c6b246a616dR14): Imported the `Result` entity and added a one-to-many relationship for `obj_qaed_user`. …
> * Feat Added QA Tracking Fields

- onecgiar-pr-server/src/api/results/entities/result.entity.ts
- onecgiar-pr-server/src/api/user-notification-settings/user-notification-settings.service.spec.ts
- onecgiar-pr-server/src/auth/modules/user/entities/user.entity.ts
- onecgiar-pr-server/src/migrations/1729692807743-AddedQATrackingColumnsForResults.ts
This pull request focuses on enhancing the validation and alert mechanisms for innovation readiness evidence in the `RdEvidencesComponent`, as well as making a minor label change in the `AnticipatedInnovationUserComponent`. The most important changes include the addition of a new validation method, updates to the component's template, and corresponding unit tests.
Improvements to validation and alerts:
* [`onecgiar-pr-client/src/app/pages/results/pages/result-detail/pages/rd-evidences/rd-evidences.component.html`](diffhunk://#diff-a990f03a7adefdd318534e530ace0ec81bc371c6e59d3865aca2eec36e8cb232R9-R15): Added a conditional alert status message to prompt users to provide evidence for innovation readiness unless the readiness level is set to 0.
* …
> *Feat. New alerts validation on evidences section and narrative changes

- onecgiar-pr-client/src/app/pages/results/pages/result-detail/pages/rd-theory-of-change/rd-theory-of-change.component.html
This pull request includes a small change to the `rd-theory-of-change.component.html` file. The change modifies the `fieldDisabled` attribute to dynamically enable or disable the field based on the length of `contributing_and_primary_initiative` and the presence of `result_toc_result.initiative_id`.
* [`onecgiar-pr-client/src/app/pages/results/pages/result-detail/pages/rd-theory-of-change/rd-theory-of-change.component.html`](diffhunk://#diff-ab624cf3fc3c8e06195937a2c07c66032a04d72d7fe7d990f8bca1e9656989c1L22-R24): Modified the `fieldDisabled` attribute to dynamically enable or disable the field based on specific conditions.
> 🐛fix(Section 2): re-adding condition on submitter dropdown. P2-1177

- onecgiar-pr-server/src/api/results/results-toc-results/repositories/results-toc-results.repository.ts
This pull request includes changes to the `onecgiar-pr-server/src/api/results/results-toc-results/repositories/results-toc-results.repository.ts` file to remove unnecessary code related to saving indicators. 
Codebase simplification:
* Removed the logic for saving indicators (`saveInditicatorsContributing`) from the `ResultsTocResultRepository` class, as it was deemed unnecessary. [[1]](diffhunk://#diff-0d4c3c693c7a4f97b734e63f5836db12a93f1655170a05d02c77f765af449ad0L2209-L2216) [[2]](diffhunk://#diff-0d4c3c693c7a4f97b734e63f5836db12a93f1655170a05d02c77f765af449ad0L2309-L2316)
> * Fix remove Indicator Target Saving Logic

- onecgiar-pr-server/src/api/contribution-to-indicators/repositories/contribution-to-indicator-result.repository.ts
- onecgiar-pr-server/src/api/contribution-to-indicators/repositories/contribution-to-indicators.repository.ts
This pull request includes several changes to the `ContributionToIndicatorResultsRepository` and `ContributionToIndicatorsRepository` classes in the `onecgiar-pr-server/src/api/contribution-to-indicators/repositories` directory. The main focus is on updating the database queries to use the correct field names and adding distinct selection and ordering to improve query results.
Changes to database queries:
* Updated the field used in the `left join` clause from `toc_result_indicator_id` to `related_node_id` in the `ContributionToIndicatorResultsRepository` class.
* Added `order by tr.id desc` to the query in the `ContributionToIndicatorResultsRepository` class to ensure results are ordered by the `id` field in descending order.
* Added `distinct` to the `select` statements to ensure unique …
> * Feat Improved queries for Contribution to Indicators

- onecgiar-pr-server/src/api/results/results-toc-results/results-toc-results.service.ts
- onecgiar-pr-server/src/api/results/share-result-request/share-result-request.service.ts
This pull request includes changes to improve the code quality and maintainability in the `onecgiar-pr-server` project. The most important changes involve simplifying conditional checks and removing commented-out code.
Code quality improvements:
* [`onecgiar-pr-server/src/api/results/results-toc-results/results-toc-results.service.ts`](diffhunk://#diff-d37e49c54f4fdd2aa65662c27bdba2bf389aea837bf6a3a58e0aa42d983d89f1L704-R704): Simplified the conditional check for `createResultsTocResultDto` by using optional chaining.
Code maintainability:
* [`onecgiar-pr-server/src/api/results/share-result-request/share-result-request.service.ts`](diffhunk://#diff-616a4d09d4dba5dfa8d0cfeaaa05a06a6eabe60d5e019105af9371a97fccca24L954-L961): Removed unnecessary commented-out code to improve readability and …
> * Feat simplify null check and remove commented-out code

- onecgiar-pr-server/src/api/contribution-to-indicators/repositories/contribution-to-indicator-result.repository.ts
This pull request includes changes to the `ContributionToIndicatorResultsRepository` class in the `onecgiar-pr-server` project. The changes focus on modifying the database query logic to use a different identifier for matching records.
Key changes include:
* Updated the join condition to use `tri.related_node_id` instead of `tri.toc_result_indicator_id` when converting `cti.toc_result_id` using `utf8mb4`.
* Modified the `where` clause to replace `tri.toc_result_indicator_id` with `tri.related_node_id` for filtering active records and ensuring `main_r.id` is not null.
* Adjusted the subquery condition to use `tri.related_node_id` instead of `tri.toc_result_indicator_id` for converting `cti.toc_result_id` using `utf8mb4`.
> * Feat Updated query to retrieve results Manual Mapped in Outcomes Indicators

- onecgiar-pr-server/src/api/results/share-result-request/share-result-request.service.ts
This pull request includes a change to the `ShareResultRequestService` class in the `share-result-request.service.ts` file. The change adds a conditional block to map work packages to an initiative if `is_map_to_toc` is not true.
* [`onecgiar-pr-server/src/api/results/share-result-request/share-result-request.service.ts`](diffhunk://#diff-616a4d09d4dba5dfa8d0cfeaaa05a06a6eabe60d5e019105af9371a97fccca24R954-R962): Added a conditional block to call `mapWorkPackagesToInitiative` if `is_map_to_toc` is false.
> * Feat Conditionally map work packages to initiative based on TOC flag

- onecgiar-pr-server/src/api/results/result_budget/repositories/result_initiative_budget.repository.ts
This pull request includes a change to the `fisicalDelete` method in the `ResultInitiativeBudgetRepository` class to improve the readability and maintainability of the SQL query.
Improvements to SQL query formatting:
* [`onecgiar-pr-server/src/api/results/result_budget/repositories/result_initiative_budget.repository.ts`](diffhunk://#diff-1b482c71ba643bfe41544337b7cd15c85bd1b8237a440b8a5b11263a08fbb31dL123-R128): Reformatted the SQL query in the `fisicalDelete` method to improve readability by restructuring the `DELETE` statement and aligning the `INNER JOIN` clause.
> *Feat Improve SQL delete query formatting for the correct parameter for Change Result Type module

- onecgiar-pr-client/src/app/pages/type-one-report/pages/tor-progress-eoio/tor-progress-eoio.component.html
- onecgiar-pr-client/src/app/pages/type-one-report/pages/tor-progress-wps/tor-progress-wps.component.html
This pull request includes updates to URLs in two HTML files to point to a new SharePoint folder.
Updated SharePoint URLs:
* [`onecgiar-pr-client/src/app/pages/type-one-report/pages/tor-progress-eoio/tor-progress-eoio.component.html`](diffhunk://#diff-7311204ddf0654ee114b7afda82f966d63765b33c47397a17c383972eae247b7L12-R12): Changed the URL in the anchor tag to the new SharePoint folder link.
* [`onecgiar-pr-client/src/app/pages/type-one-report/pages/tor-progress-wps/tor-progress-wps.component.html`](diffhunk://#diff-4e2e4114ebc5d163cf9260a838286123af55c05adb8d9546b0f5588c276e7f97L17-R17): Changed the URL in the anchor tag to the new SharePoint folder link.
> ♻️ refactor(type-one-report): Update SharePoint folder links in EOIO and WPS progress components

- onecgiar-pr-client/src/app/pages/results/pages/results-outlet/pages/results-list/results-list.component.spec.ts
- onecgiar-pr-client/src/app/pages/results/pages/results-outlet/pages/results-list/results-list.component.ts
This pull request includes changes to the `ResultsListComponent` to update the cell number for the `pdf_link` key in the export to Excel functionality.
* [`onecgiar-pr-client/src/app/pages/results/pages/results-outlet/pages/results-list/results-list.component.spec.ts`](diffhunk://#diff-7b1dde36da3a1e76e3ab9dca2bf7769c202c03b4f188a6c5db1b6347e6367c16L294-R294): Updated the expected cell number for `pdf_link` from 22 to 23 in the test case.
* [`onecgiar-pr-client/src/app/pages/results/pages/results-outlet/pages/results-list/results-list.component.ts`](diffhunk://#diff-a7dc5bb80e2120a4871101ce862973d571ef7d62e0c85ea16f29232f585eb86bL145-R145): Updated the cell number for `pdf_link` from 22 to 23 in the export to Excel method.
> 🐛 fix(results-list): Update Excel export column count for PDF link

- onecgiar-pr-server/src/api/contribution-to-indicators/repositories/contribution-to-indicator-result.repository.ts
- onecgiar-pr-server/src/api/contribution-to-indicators/repositories/contribution-to-indicators.repository.ts
This pull request includes changes to the `ContributionToIndicatorResultsRepository` and `ContributionToIndicatorsRepository` classes to simplify query handling and improve code maintainability. The most important changes include the removal of unnecessary parameters from query methods and the refactoring of query construction.
Improvements to query handling:
* [`onecgiar-pr-server/src/api/contribution-to-indicators/repositories/contribution-to-indicator-result.repository.ts`](diffhunk://#diff-b9bcd224b96e07a95954de4afedffa682e35adb5d39cb191e8a21cdc8cd32bbaL99-R98): Removed the `tocId` parameter from the `getContributingResultsQuery` method and replaced inline parameter substitution with parameterized queries. [[1]](diffhunk://#diff-b9bcd224b96e07a95954de4afedffa682e35adb5d39cb191e8a21cdc8 …
> * Fix Update SQL queries to use parameterized inputs and improve query structure

- onecgiar-pr-client/src/app/pages/ipsr/pages/innovation-package-detail/components/ipsr-submission-modal/ipsr-submission-modal.component.spec.ts
- onecgiar-pr-client/src/app/pages/ipsr/pages/innovation-package-detail/components/ipsr-submission-modal/ipsr-submission-modal.component.ts
- onecgiar-pr-client/src/app/pages/ipsr/pages/innovation-package-detail/components/ipsr-unsubmit-modal/ipsr-unsubmit-modal.component.spec.ts
- onecgiar-pr-client/src/app/pages/ipsr/pages/innovation-package-detail/components/ipsr-unsubmit-modal/ipsr-unsubmit-modal.component.ts
- onecgiar-pr-client/src/app/pages/ipsr/pages/innovation-package-detail/innovation-package-detail.component.html
This pull request updates the `IpsrSubmissionModalComponent` and `IpsrUnsubmitModalComponent` to replace the `status` property with `status_id` for better clarity and consistency. Additionally, it refactors the `innovation-package-detail.component.html` file to improve functionality and maintainability.
* Replaced the `status` property with `status_id` in the mock services and test assertions to align with the updated API response structure. (`onecgiar-pr-client/src/app/pages/ipsr/pages/innovation-package-detail/components/ipsr-submission-modal/ipsr-submission-modal.component.spec.ts`: [[1]](diffhunk://#diff-869d73c56096740bab86b024537a59f918696a35a14ef6b803bee5098eb98811L29-R29) [[2]](diffhunk://#diff-869d73c56096740bab86b024537a59f918696a35a14ef6b803bee5098eb98811L40-R40) …
> * Feat update status handling to use status_id for consistency across submission and un-submit modals

- onecgiar-pr-server/src/auth/Middlewares/jwt.middleware.spec.ts
- onecgiar-pr-server/src/auth/Middlewares/jwt.middleware.ts
- onecgiar-pr-server/src/auth/auth.service.spec.ts
This pull request includes minor changes to the `JwtMiddleware` and `AuthService` files, primarily focused on improving code readability and removing redundant properties.
* [`onecgiar-pr-server/src/auth/auth.service.spec.ts`](diffhunk://#diff-207c5b522bcf2f212d0bddbfb32ab6dfe07d720418519ceb19f04da0bd1273fbL372-R374): Reformatted the `expect(result.message)` assertion to improve readability by breaking the string into multiple lines.
* [`onecgiar-pr-server/src/auth/Middlewares/jwt.middleware.spec.ts`](diffhunk://#diff-c6a648ef71eaeed3f9d344449ddf9b9a115bdfc45d280d521c8bdddbaa8c6d99L353): Removed the `expiresIn` property from the test configuration for JWT middleware.
* [`onecgiar-pr-server/src/auth/Middlewares/jwt.middleware.ts`](diffhunk://#diff-7b356069a9ac959d0e8154b813d59040dfc8ce943ac …
> ♻️ Improved expiresIn option from JWT middleware

- .github/workflows/jenkins-trigger.yml
- .github/workflows/jenkins-triggeryml.backup
This pull request updates the Jenkins workflow configuration to support matrix builds and streamline triggering for specific branches. Additionally, a backup of the original workflow configuration has been added for reference.
* **Matrix Builds for Jenkins Jobs**: The workflow now uses a matrix strategy to trigger multiple Jenkins jobs (`prms-reporting-tool-dev-docker` and `prms-reporting-tool-dev-client-docker`) with parameters. This allows for more flexible and parallelized builds. (`.github/workflows/jenkins-trigger.yml`, [.github/workflows/jenkins-trigger.ymlL1-L27](diffhunk://#diff-ece632ebc3c8f5f8c8fff3f5547d814124811ea82711e33ee81616f8bcd784bfL1-L27))
* **Branch-Specific Triggers**: The workflow has been updated to trigger only on the `dev` branch for both `push` and `pull_request` …
> ♻️ Update Jenkins trigger workflow to specify branch and improve URL construction

- onecgiar-pr-client/Dockerfile
This pull request updates the `onecgiar-pr-client/Dockerfile` to set the timezone to Europe/Berlin (CET) in both the build and testing stages. This ensures consistent timezone settings across the application environment.
Environment configuration updates:
* Added timezone configuration (`Europe/Berlin`) to the build stage of the Dockerfile to standardize the environment.
* Added timezone configuration (`Europe/Berlin`) to the testing stage of the Dockerfile to maintain consistency during testing.
> ♻️ Refactor: Add timezone configuration to Dockerfile for build and test stages

- .github/workflows/jenkins-trigger.yml
This pull request updates the Jenkins workflow configuration in `.github/workflows/jenkins-trigger.yml` to better align with the branching strategy and introduces separate steps for triggering backend and frontend Jenkins jobs.
* Changed the workflow name from "Trigger Jenkins Job" to "Trigger Jenkins Docker" to reflect its purpose more accurately.
* Limited the workflow triggers to the `dev` branch for both `push` and `pull_request` events, instead of triggering on all branches.
* Added a new step specifically for triggering the backend Jenkins job (`prms-reporting-tool-dev-docker`) with a dynamically built URL. This includes setting the `JENKINS_URL` environment variable and using `curl` with Jenkins credentials from GitHub secrets.
* Updated the existing frontend Jenkins job step to …
> ♻️ Refactor: Update Jenkins trigger workflow for specific branch handling and improve job naming

- onecgiar-pr-client/src/app/pages/results/pages/result-detail/pages/rd-evidences/rd-evidences.component.ts
This pull request adds a helpful resource for users by including a video tutorial link in the guidance text for creating evidence entries.
* [`onecgiar-pr-client/src/app/pages/results/pages/result-detail/pages/rd-evidences/rd-evidences.component.ts`](diffhunk://#diff-9108f6bada7868034992f3f6248c28a0d850172763d8c63a4a7377533060d937L27-R29): Added a new list item with a link to a video tutorial to provide users with additional guidance on creating evidence entries.
> P2 1663 hyperlink for video guide on evidence section

- onecgiar-pr-client/Dockerfile
This pull request makes a small update to the `onecgiar-pr-client/Dockerfile` to improve the Docker build process. The main change is moving the `npm ci` command to run immediately after copying the `package*.json` files, which ensures that dependencies are installed before the application source code is copied.
* Moved the `npm ci` command to run directly after copying `package*.json` files, ensuring dependencies are installed before copying the rest of the application files. [[1]](diffhunk://#diff-1de450f85dadad709fd1a742606a84460d76f0b4f3b886523e2ae5322f49bbddL13-L17) [[2]](diffhunk://#diff-1de450f85dadad709fd1a742606a84460d76f0b4f3b886523e2ae5322f49bbddL34-L38)
> chore(dockerfile): Refactor Dockerfile for improved clarity and consistency

- onecgiar-pr-client/Dockerfile
This pull request makes a minor adjustment to the `onecgiar-pr-client/Dockerfile` by changing the way npm dependencies are installed. The installation command is switched from `npm ci` to `npm i` to improve compatibility or address team requirements.
* Dockerfile dependency installation: Changed the command from `npm ci` to `npm i` after copying project files, both for building and testing steps. [[1]](diffhunk://#diff-1de450f85dadad709fd1a742606a84460d76f0b4f3b886523e2ae5322f49bbddL17-R17) [[2]](diffhunk://#diff-1de450f85dadad709fd1a742606a84460d76f0b4f3b886523e2ae5322f49bbddL38-R38)
> chore: update Dockerfile for improved build and test stages

- onecgiar-pr-client/src/app/pages/results/pages/result-creator/components/result-ai-assistant/result-ai-assistant.component.spec.ts
- onecgiar-pr-client/src/app/pages/results/pages/result-creator/components/result-ai-assistant/result-ai-assistant.component.ts
This pull request updates the file upload and mining logic in the `ResultAiAssistantComponent` to use a new S3 bucket and a more structured file key path. The changes ensure that files are stored in the `ai-services-ibd` bucket under a specific folder, improving organization and consistency. Unit tests have been updated to reflect these changes.
**File upload and mining logic updates:**
* Changed the S3 bucket name from `'microservice-mining'` to `'ai-services-ibd'` in both `createUploadFormData` and `createMiningFormData` methods in `result-ai-assistant.component.ts`. [[1]](diffhunk://#diff-d9a1d83f4d4fc0e72718b5807a23f4db82d26d008ce7d393b90f3453ed86c2b3L120-R121) [[2]](diffhunk://#diff-d9a1d83f4d4fc0e72718b5807a23f4db82d26d008ce7d393b90f3453ed86c2b3L166-R168)
* Updated the file key in …
> ♻️ Refactor(result-ai-assistant) P2-1755: Update bucket name and key for form data submission
